import { Router, type IRouter } from "express";
import healthRouter from "./health";
import teacherReviewRouter from "./teacher-review";
import sourceReviewRouter from "./source-review";
import mateenRouter from "./mateen";
import scholarlyRouter from "./scholarly";
import recitationRouter from "./recitations";
import assessmentRouter from "./assessments";
import recitationPagesRouter from "./recitation-pages";
import practiceReportsRouter from "./practice-reports";
import learningStagesRouter from "./learning-stages";
import studyActivityRouter from "./study-activity";
import wordPracticeRouter from "./word-practice";
import dailyPlanRouter from "./daily-plan";

const router: IRouter = Router();
router.use(healthRouter);
router.use(recitationPagesRouter);
router.use(practiceReportsRouter);
router.use(learningStagesRouter);
router.use(studyActivityRouter);
router.use(wordPracticeRouter);
router.use(dailyPlanRouter);
router.use(teacherReviewRouter);
router.use(sourceReviewRouter);
router.use(mateenRouter);
router.use(scholarlyRouter);
router.use(recitationRouter);
router.use(assessmentRouter);
export default router;
