import { Router, type IRouter } from "express";
import healthRouter from "./health";
import teacherReviewRouter from "./teacher-review";
import sourceReviewRouter from "./source-review";
import mateenRouter from "./mateen";
import scholarlyRouter from "./scholarly";
import recitationRouter from "./recitations";
import assessmentRouter from "./assessments";
import recitationPagesRouter from "./recitation-pages";

const router: IRouter = Router();
router.use(healthRouter);
router.use(recitationPagesRouter);
router.use(teacherReviewRouter);
router.use(sourceReviewRouter);
router.use(mateenRouter);
router.use(scholarlyRouter);
router.use(recitationRouter);
router.use(assessmentRouter);
export default router;
