import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowLeft, Check, ChevronDown, ChevronLeft, Copy, Menu, Moon, Play, Send, Share2, Sparkles, Sun, Volume2, VolumeX, X } from 'lucide-react';
import { Link } from 'wouter';
import logoPath from '@assets/MateeeeeeeeenLOGO_1790090010886.png';

type Theme = 'parchment' | 'night';
type AuthState = { open: boolean; tab: 'student' | 'teacher'; mode: 'login' | 'register' };

const features = [
  ['التصحيح الصوتي اللحظي','دقة صوتية فائقة','نموذج تعرّف صوتي استثنائي خُصص للنطق العربي الفصيح وقواعد القراءة. يستمع لتسميع الطالب حرفاً فحرفاً، ويكتشف أخطاء الحركات والتشكيل والإعراب فور النطق بها دون تأخير.'],
  ['المساعد التفاعلي مَتِين','شروح موثقة','اسأل المساعد الذكي عن أي لفظ غريب، أو إعراب معضل، أو استفسار عقدي أو فقهي، وسيجيبك في ثوانٍ مستنداً إلى أمهات الشروح المعتمدة لكل متن، مع العزو الدقيق للجزء والصفحة.'],
  ['توجيه بشري موثوق','توجيه بشري','التقنية وسيلة إتقان وتمكين وليست بديلاً عن الشيخ المعلم؛ توفر المنصة ربطاً مباشراً بشبكة من المقرئين المتقنين والمشايخ المجازين للتوجيه والإجابة عن الأسئلة المعقدة.'],
  ['تلقين صوتيات المتقنين','استمع وكرر','مكتبة صوتية نقية تضم تلاوات وقراءات لأكابر القراء والمشايخ المحققين، تتيح لك خاصية التكرار الذكي والمضاهاة الصوتية لترسيخ اللفظ السليم في ذاكرتك.'],
  ['متابعة وتحليل المستوى','تكرار متباعد','لوحة تحليلات ذكية ترصد منحنى أدائك وتحدد الكلمات التي يتكرر فيها ترددك، وتجدول لك مراجعات دورية ذكية متباعدة لضمان عدم نسيان ما حفظته.'],
  ['تدرج في التعلم','تأصيل منهجي','خطة دراسية أصيلة تبدأ بصغار المتون قبل كبارها، من المستوى التمهيدي وحتى المنظومات المتقدمة والمطولات، تحصيناً للطالب من التشتت وسيراً على سنن العلماء في التلقي.'],
  ['اختبار تحديد المستوى','اختصر وقتك','لا تبدأ من الصفر إذا كنت حافظاً؛ خُض اختباراً تشخيصياً تفاعلياً يقيس بدقة مستواك ليوجهك مباشرة إلى المرحلة التي تناسب حصيلتك العلمية.'],
];
const faqs = [
  ['هل يغني الذكاء الاصطناعي في المنصة عن التلقي من المشايخ؟','قطعاً لا؛ إنما هو مساعد ذكي ومرافق يضبط لك الأوقات التي لا تجد فيها شيخاً يسمع لك، ويصحح لك أخطاء التشكيل والحفظ الأولية، حتى إذا رسخ حفظك عُرضت قراءتك النهائية على الشيوخ المعتمدين للإجازة.'],
  ['كيف تضمن المنصة صحة إجابات المساعد «مَتِين» وعدم خطئه في الفتوى؟','تم بناء المساعد عبر تقنية الـ RAG الصارمة والمغلقة، بحيث لا يولد إجابات من خياله، بل يستخرج النصوص نصياً من الشروح المعتمدة فقط مع ذكر الكتاب والصفحة، ولا يفتي في النوازل المعاصرة بل يحيل إلى العلماء.'],
  ['هل المنصة مجانية أم تتطلب اشتراكاً؟','مسارات الحفظ الأساسية والمحاكي الصوتي اللحظي متاحة كوقف علمي مجاني لجميع طلاب العلم حول العالم، وهناك خدمات توجيه شخصي مكثف ودورات إجازة خاصة يدعم ريعها البنية السحابية للمشروع.'],
  ['كيف أبدأ الدراسة كطالب، وهل يلزم التسجيل الفوري؟','يمكنك البدء فوراً بالنقر على زر «اختبار تحديد المستوى» لتقييم حفظك في 3 دقائق، أو الضغط على «التسجيل كطالب» لإنشاء حساب وتتبع محفوظاتك عبر لوحة تحليلاتك الشخصية.'],
];

function SectionTitle({ badge, title, text }: { badge: string; title: string; text: string }) {
  return <div className="mx-auto mb-14 max-w-2xl text-center"><span className="mb-4 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-2 text-xs font-bold text-primary"><Sparkles size={13}/>{badge}</span><h2 className="font-arabic text-4xl font-bold leading-tight md:text-5xl">{title}</h2><p className="mt-4 leading-8 text-muted-foreground">{text}</p></div>;
}

export function MateenLanding() {
  const [theme, setTheme] = useState<Theme>('parchment');
  const [auth, setAuth] = useState<AuthState>({open:false, tab:'student', mode:'login'});
  const [assistant, setAssistant] = useState(false);
  const [audio, setAudio] = useState(false);
  const [toast, setToast] = useState('');
  useEffect(() => { document.documentElement.classList.toggle('dark', theme === 'night'); document.documentElement.dir='rtl'; }, [theme]);
  const openAuth = (tab:'student'|'teacher', mode:'login'|'register'='register') => setAuth({open:true,tab,mode});
  const notify = (m:string) => { setToast(m); window.setTimeout(()=>setToast(''),2600); };
  return <div className="grain min-h-dvh overflow-hidden">
    <Navbar theme={theme} setTheme={setTheme} audio={audio} setAudio={setAudio} openAuth={openAuth} onAssistant={()=>setAssistant(true)} />
    <main>
      <Hero openAuth={openAuth} />
      <Features openAuth={openAuth} />
      <Hadith notify={notify} />
      <Tracks />
      <Methodology />
      <FAQ />
      <CTA openAuth={openAuth} />
    </main>
    <Footer />
    <button onClick={()=>setAssistant(true)} aria-label="فتح مساعد متين" data-testid="button-open-assistant" className="fixed bottom-5 left-5 z-40 flex items-center gap-2 rounded-full border border-primary/30 bg-card px-4 py-3 text-sm font-bold text-primary shadow-xl transition hover:-translate-y-1"><Sparkles size={17}/>اسأل مَتِين</button>
    <AnimatePresence>{auth.open && <AuthModal state={auth} setState={setAuth}/>} {assistant && <Assistant close={()=>setAssistant(false)} openAuth={()=>{setAssistant(false);openAuth('student','login')}}/>}</AnimatePresence>
    <AnimatePresence>{toast && <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:20}} className="fixed bottom-5 right-5 z-50 flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground shadow-xl"><Check size={17}/>{toast}</motion.div>}</AnimatePresence>
  </div>;
}

function Navbar({theme,setTheme,audio,setAudio,openAuth,onAssistant}:{theme:Theme;setTheme:(x:Theme)=>void;audio:boolean;setAudio:(x:boolean)=>void;openAuth:(a:'student'|'teacher',b:'login'|'register')=>void;onAssistant:()=>void}) {
  const [menu,setMenu]=useState(false);
  const links=[['عن المنصة','/about'],['المحاكي الذكي','#smart-emulator'],['مزايا المنصة','#features'],['المسارات الحالية','#tracks'],['منهجية العمل','#methodology'],['الأسئلة الشائعة','#faq']];
  return <header className="sticky top-0 z-30 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3"><Link href="/" className="flex items-center gap-2" data-testid="link-home"><img src={logoPath} alt="مَتِين" className="brand-logo h-12 w-[9.5rem] object-contain" /></Link><nav className="hidden items-center gap-5 lg:flex">{links.map(([label,href])=><Link key={href} href={href} data-testid={`link-nav-${label}`} className="text-[13px] font-semibold text-muted-foreground transition hover:text-primary">{label}</Link>)}</nav><div className="flex items-center gap-2"><button onClick={()=>setAudio(!audio)} aria-label={audio?'كتم الصوت':'تشغيل الصوت'} data-testid="button-audio" className="rounded-md p-2 transition hover:bg-primary/10">{audio?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button onClick={()=>setTheme(theme==='night'?'parchment':'night')} aria-label="تبديل المظهر" data-testid="button-theme" className="rounded-md p-2 transition hover:bg-primary/10">{theme==='night'?<Sun size={18}/>:<Moon size={18}/>}</button><button onClick={()=>openAuth('student','login')} data-testid="button-login" className="hidden rounded-md bg-primary px-4 py-2 text-sm font-bold text-primary-foreground shadow-md transition hover:-translate-y-0.5 sm:block">تسجيل الدخول</button><button onClick={()=>setMenu(!menu)} className="rounded-md p-2 lg:hidden" aria-label="القائمة" data-testid="button-menu">{menu?<X/>:<Menu/>}</button></div></div>{menu&&<nav className="space-y-1 border-t border-border px-5 pb-4 pt-2 lg:hidden">{links.map(([l,h])=><Link onClick={()=>setMenu(false)} key={h} href={h} className="block rounded-lg px-3 py-3 text-sm font-semibold hover:bg-primary/10">{l}</Link>)}<button onClick={()=>openAuth('student','login')} className="mt-2 w-full rounded-md bg-primary py-3 font-bold text-primary-foreground">تسجيل الدخول</button></nav>}</header>;
}

function Hero({openAuth}:{openAuth:(a:'student'|'teacher',b:'login'|'register')=>void}) {
  return <section className="relative"><div className="absolute inset-0 -z-10 ornament opacity-60"/><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-16 pt-20 lg:grid-cols-[1.05fr_.95fr] lg:pb-24 lg:pt-28"><motion.div initial={{opacity:0,x:25}} animate={{opacity:1,x:0}} transition={{duration:.7}}><span className="inline-flex rounded-full border border-accent/40 bg-accent/10 px-4 py-2 text-xs font-bold text-secondary">المنصة الذكية الأولى المتخصصة في متون ومنظومات علوم الشريعة</span><h1 className="font-arabic mt-7 max-w-xl text-6xl font-bold leading-[1.1] md:text-8xl">مساعدك الذكي<br/><span className="text-primary">للحفظ المتين</span></h1><p className="mt-7 max-w-2xl text-base leading-9 text-muted-foreground md:text-lg">نجمع بين جلال المتون العلمية ورسوخ شروحها الأثرية، وأحدث خوارزميات الاستماع الصوتي والذكاء الاصطناعي التوليدي. صحّح قراءتك وتشكيلك لحظياً، وتلقّ الدعم والتوجيه من المشائخ المتقنين بالمنصة.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={()=>openAuth('student','register')} data-testid="button-student-register" className="rounded-xl bg-primary px-6 py-3.5 font-bold text-primary-foreground shadow-lg transition hover:-translate-y-1">التسجيل كطالب <ArrowLeft className="mr-2 inline" size={17}/></button><button onClick={()=>openAuth('teacher','register')} data-testid="button-teacher-register" className="rounded-xl border border-primary/30 bg-card px-6 py-3.5 font-bold text-primary transition hover:-translate-y-1">التسجيل كمعلم وموجه</button></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-muted-foreground"><span>شروح محققة</span><span className="text-accent">✦</span><span>تصحيح لحظي</span><span className="text-accent">✦</span><span>توجيه ودعم بشري عند الحاجة</span></div></motion.div><Simulator/></div></section>;
}

function Simulator() {
  const [track,setTrack]=useState('الأصول الثلاثة'); const [playing,setPlaying]=useState(false); const [mic,setMic]=useState(false); const [speed,setSpeed]=useState('١×');
  return <motion.div id="smart-emulator" initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="relative overflow-hidden rounded-[2rem] border border-primary/20 bg-card p-5 shadow-2xl shadow-primary/10 sm:p-7"><div className="absolute -left-16 -top-16 h-40 w-40 rounded-full bg-accent/10 blur-3xl"/><div className="relative flex items-center justify-between"><div><p className="text-xs font-bold tracking-widest text-primary">المحاكي الصوتي</p><h3 className="font-arabic mt-1 text-2xl font-bold">جلسة تسميع حيّة</h3></div><span className="flex items-center gap-2 text-xs text-muted-foreground"><i className="h-2 w-2 rounded-full bg-primary"/>يعمل الآن</span></div><label className="mt-7 block text-xs font-bold text-muted-foreground">اختر المتن</label><select value={track} onChange={e=>setTrack(e.target.value)} data-testid="select-track" className="mt-2 w-full rounded-xl border bg-background px-4 py-3 outline-none focus:ring-2 focus:ring-primary"><option>الأصول الثلاثة</option><option>تحفة الأطفال</option></select><div className="manuscript-lines mt-5 rounded-2xl border bg-background/70 p-5"><p className="text-xs text-muted-foreground">من متن {track}</p><p className="font-arabic mt-4 text-2xl leading-loose">اعلم رحمك الله أنه يجب علينا <span className="rounded bg-accent/15 px-1 text-secondary underline decoration-wavy decoration-accent">التعلم</span> أربع مسائل</p><div className="wave mt-5 flex h-10 items-center justify-center gap-1.5">{Array.from({length: thirty(26)}).map((_,i)=><span key={i} className="h-8 w-1 rounded-full bg-primary/60" style={{height:`${12+(i%7)*5}px`}}/>)}</div></div><div className="mt-5 flex items-center justify-between"><button onClick={()=>setPlaying(!playing)} data-testid="button-demo-play" className="flex h-11 w-11 items-center justify-center rounded-full bg-primary text-primary-foreground">{playing?<span className="text-lg">Ⅱ</span>:<Play size={17} fill="currentColor"/>}</button><button onClick={()=>setMic(!mic)} data-testid="button-microphone" className={`rounded-xl border px-4 py-2 text-sm font-bold ${mic?'bg-primary text-primary-foreground':'bg-background'}`}>{mic?'يستمع الآن':'فعّل الميكروفون'}</button><button onClick={()=>setSpeed(speed==='١×'?'٠٫٧٥×':speed==='٠٫٧٥×'?'١٫٥×':'١×')} data-testid="button-speed" className="rounded-xl border px-4 py-2 text-sm font-bold">{speed}</button></div></motion.div>;
}
const thirty=(n:number)=>n;

function Features({openAuth}:{openAuth:(a:'student'|'teacher',b:'login'|'register')=>void}) { return <section id="features" className="mx-auto max-w-7xl px-5 py-24"><SectionTitle badge="ركائز الإتقان" title="دليلك الشامل نحو الإتقان والرسوخ" text="سبع ركائز بنيت عليها منصة متين لتجمع بين أصالة الحلقات، وأحدث ما توصلت إليه تقنيات الذكاء الاصطناعي التوليدي."/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map((f,i)=><motion.article key={f[0]} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} transition={{delay:i*.05}} viewport={{once:true}} className={`group rounded-2xl border bg-card p-6 transition hover:-translate-y-1 hover:border-primary/40 hover:shadow-xl ${i===0?'lg:row-span-2 lg:p-8':''}`}><span className="text-xs font-bold text-accent">{String(i+1).padStart(2,'0')} / {f[1]}</span><h3 className="font-arabic mt-5 text-2xl font-bold">{f[0]}</h3><p className="mt-3 text-sm leading-8 text-muted-foreground">{f[2]}</p>{i===6&&<button onClick={()=>openAuth('student','register')} className="mt-6 flex items-center gap-2 rounded-lg bg-secondary px-4 py-2 text-sm font-bold text-secondary-foreground" data-testid="button-diagnostic-test">ابدأ الاختبار التشخيصي الآن <ArrowLeft size={15}/></button>}</motion.article>)}</div></section>; }

function Hadith({notify}:{notify:(x:string)=>void}) { const text='«مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا؛ سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ»'; const act=async()=>{await navigator.clipboard?.writeText(`${text}\nصحيح مسلم`);notify('نُسخ الحديث ومصدره');}; return <section className="border-y border-primary/15 bg-primary/5 px-5 py-24 text-center"><span className="text-sm font-bold text-primary">قال رسول الله ﷺ</span><blockquote className="font-arabic mx-auto mt-7 max-w-4xl text-3xl font-bold leading-[2] md:text-5xl">{text}</blockquote><p className="mt-5 text-sm text-muted-foreground">صحيح مسلم</p><div className="mt-8 flex justify-center gap-3"><button onClick={act} className="flex items-center gap-2 rounded-lg border bg-card px-4 py-2 text-sm font-bold" data-testid="button-copy-hadith"><Copy size={15}/>نسخ الحديث</button><button onClick={async()=>{if(navigator.share) await navigator.share({text}); else await act()}} className="flex items-center gap-2 rounded-lg border bg-card px-4 py-2 text-sm font-bold" data-testid="button-share-hadith"><Share2 size={15}/>مشاركة</button></div></section>; }

function Tracks(){const tracks=[['مسار العقيدة','رسوخ التوحيد والأدلة','دراسة متدرجة لأهم المتون العقائدية المحررة لتأصيل طالب العلم في أبواب التوحيد والإيمان ومسائل الاعتقاد على منهج السلف الصالح.','نواقض الإسلام، القواعد الأربعة'],['مسار التجويد والقراءات','إتقان التلاوة وضبط الحروف','مسار متخصص لضبط أحكام التلاوة ومخارج الحروف، ودراسة المنظومات العلمية الضابطة للأداء الصوتي السليم.','تحفة الأطفال'],['مسار الحديث','أصول الرواية وقواعد الأثر','استكشاف واستظهار أمهات المتون الحديثية لتأسيس طالب العلم في السنة النبوية الشريفة ومعرفة جوامع الكلم.','الأربعون النووية']]; return <section id="tracks" className="mx-auto max-w-7xl px-5 py-24"><SectionTitle badge="المناهج العلمية بالمنصة" title="المسارات النشطة" text="اختر مسارك العلمي لتبدأ رحلة الحفظ المنهجي والتلقين الصوتي اللحظي عبر متون محققة على أيدي علماء الأمة."/><div className="grid gap-5 md:grid-cols-3">{tracks.map((t,i)=><article key={t[0]} className="group relative min-h-[295px] overflow-hidden rounded-3xl border bg-card p-7"><div className="absolute -left-10 -top-10 h-32 w-32 rounded-full border border-primary/20 transition group-hover:scale-[2.5]"/><span className="relative text-sm font-bold text-accent">٠{i+1}</span><h3 className="font-arabic relative mt-6 text-3xl font-bold">{t[0]}</h3><p className="relative mt-2 text-sm font-bold text-primary">{t[1]}</p><p className="relative mt-5 text-sm leading-8 text-muted-foreground">{t[2]}</p><p className="absolute bottom-6 right-7 text-xs font-bold text-secondary opacity-0 transition group-hover:opacity-100">{t[3]}</p></article>)}</div></section>; }

function Methodology(){const items=[['01','محرك النطق الصوتي','نموذج تعلم عميق مخصص للصوتيات العربية ومخارج الحروف وقواعد النطق، يحلل تسميع الطالب للمتون والمنظومات العلمية وحروفها بدقة عالية، ويطابق النطق مع التشكيل والضبط المعتمد.'],['02','محرك RAG للشروحات المحققة','قاعدة بيانات شعاعية تفهرس آلاف الصفحات من أمهات شروح المتون، وتسترجع النص الحرفي الدقيق بدلاً من التوليد العشوائي، لتجنب الوهم والخطأ.'],['03','التدخل البشري عند الحاجة','لوحة مخصصة للمشايخ المتقنين تتيح لهم الإجابة عن الأسئلة عند إحالة الطالب إليهم، والرد على الاستفسارات المباشرة، وتوجيه وإرشاد طلاب المنصة.']];return <section id="methodology" className="bg-secondary px-5 py-24 text-secondary-foreground"><div className="mx-auto max-w-7xl"><SectionTitle badge="الهندسة البرمجية والأصالة التراثية" title="كيف تعمل منصة مَتِين؟" text="معمارية متكاملة ثلاثية الأركان تضم دقة الفتوى وصحة التلاوة وحفظ المتون دون أي خلل."/><div className="grid gap-0 md:grid-cols-3">{items.map(x=><div key={x[0]} className="border-t border-secondary-foreground/20 p-7 md:border-l md:border-t-0"><span className="font-mono text-4xl text-accent">{x[0]}</span><h3 className="font-arabic mt-8 text-2xl font-bold">{x[1]}</h3><p className="mt-4 text-sm leading-8 opacity-75">{x[2]}</p></div>)}</div></div></section>; }

function FAQ(){const [active,setActive]=useState<number|null>(0);return <section id="faq" className="mx-auto max-w-4xl px-5 py-24"><SectionTitle badge="إجابات شافية" title="الأسئلة الشائعة" text="كل ما تود معرفته عن آلية الحفظ، ودقة الذكاء الاصطناعي، والإشراف الشرعي."/><div className="space-y-3">{faqs.map((f,i)=><div key={f[0]} className="overflow-hidden rounded-2xl border bg-card"><button onClick={()=>setActive(active===i?null:i)} aria-expanded={active===i} className="flex w-full items-center justify-between gap-4 px-6 py-5 text-right font-bold" data-testid={`button-faq-${i}`}>{f[0]}<ChevronDown className={`shrink-0 transition ${active===i?'rotate-180 text-primary':''}`}/></button><AnimatePresence>{active===i&&<motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}><p className="px-6 pb-6 text-sm leading-8 text-muted-foreground">{f[1]}</p></motion.div>}</AnimatePresence></div>)}</div></section>; }

function CTA({openAuth}:{openAuth:(a:'student'|'teacher',b:'login'|'register')=>void}){return <section className="mx-5 mb-20 overflow-hidden rounded-[2rem] bg-primary px-6 py-16 text-center text-primary-foreground md:px-20"><div className="mx-auto max-w-3xl"><h2 className="font-arabic text-4xl font-bold md:text-5xl">ابدأ رحلتك المباركة في حفظ متون ومنظومات علوم الشريعة اليوم</h2><p className="mx-auto mt-5 max-w-xl leading-8 opacity-80">كن من أوائل المنضمين لضبط محفوظاتك وتأسيس علمك المنهجي عبر أحدث تقنيات الذكاء الاصطناعي الموجهة لخدمة العلوم الشرعية.</p><button onClick={()=>openAuth('student','register')} className="mt-8 rounded-xl bg-background px-7 py-3.5 font-bold text-foreground shadow-lg" data-testid="button-final-register">سجل كطالب مجاناً</button></div></section>; }

function Footer(){return <footer className="border-t px-5 py-12"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[1.4fr_1fr_1fr]"><div><img src={logoPath} alt="مَتِين" className="brand-logo h-16 w-44 object-contain object-right" /><p className="mt-4 max-w-md text-sm leading-8 text-muted-foreground">مَتِين؛ أول منصة تعليمية تفاعلية تدمج بين أصالة المتون العلمية وتقنيات الذكاء الاصطناعي الحديثة لخدمة طالب العلم وتأصيله وضبط قراءته ومحفوظاته بإشراف مشايخ موثوقين.</p></div><div><h3 className="font-bold">مسارات العلم</h3><div className="mt-4 space-y-3 text-sm text-muted-foreground"><a href="#tracks" className="block hover:text-primary">مسار العقيدة</a><a href="#tracks" className="block hover:text-primary">مسار التجويد والقراءات</a><a href="#tracks" className="block hover:text-primary">مسار الحديث</a></div></div><div><h3 className="font-bold">في المنصة</h3><div className="mt-4 space-y-3 text-sm text-muted-foreground"><a href="#smart-emulator" className="block hover:text-primary">المحاكي الصوتي التفاعلي</a><a href="#methodology" className="block hover:text-primary">منهجية العمل</a><a href="#faq" className="block hover:text-primary">الأسئلة الشائعة</a></div></div></div><div className="mx-auto mt-12 max-w-7xl border-t pt-5 text-xs text-muted-foreground"><p>© 2026 منصة متين (Mateen) التعليمية. جميع الحقوق محفوظة لخدمة علوم الشريعة.</p><p className="mt-2">خالية تماماً من ذوات الأرواح • معايير إمكانية الوصول WCAG 2.2 AA</p></div></footer>; }

function AuthModal({state,setState}:{state:AuthState;setState:(x:AuthState)=>void}){const [sent,setSent]=useState(false);return <motion.div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/50 p-4 backdrop-blur-sm" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div role="dialog" aria-modal="true" initial={{scale:.96,y:10}} animate={{scale:1,y:0}} className="w-full max-w-lg rounded-3xl border bg-card p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div><p className="text-sm font-bold text-primary">منصة مَتِين</p><h2 className="font-arabic mt-1 text-3xl font-bold">{state.mode==='login'?'مرحباً بعودتك':'ابدأ رحلتك العلمية'}</h2></div><button onClick={()=>setState({...state,open:false})} aria-label="إغلاق" data-testid="button-close-auth"><X/></button></div><div className="mt-7 grid grid-cols-2 rounded-xl bg-muted p-1"><button onClick={()=>setState({...state,tab:'student'})} className={`rounded-lg py-2 text-sm font-bold ${state.tab==='student'?'bg-card text-primary shadow':''}`}>حساب طالب علم</button><button onClick={()=>setState({...state,tab:'teacher'})} className={`rounded-lg py-2 text-sm font-bold ${state.tab==='teacher'?'bg-card text-primary shadow':''}`}>طلب انضمام معلم/موجه</button></div><div className="mt-5 flex justify-center gap-5 text-sm"><button onClick={()=>setState({...state,mode:'login'})} className={state.mode==='login'?'font-bold text-primary underline':''}>تسجيل الدخول</button><button onClick={()=>setState({...state,mode:'register'})} className={state.mode==='register'?'font-bold text-primary underline':''}>إنشاء حساب</button></div>{sent?<div className="mt-8 rounded-2xl bg-primary/10 p-7 text-center"><Check className="mx-auto text-primary"/><p className="font-arabic mt-3 text-xl font-bold">تم استلام طلبك</p><p className="mt-2 text-sm text-muted-foreground">هذه تجربة محلية للواجهة، وستكون جاهزاً للبدء قريباً.</p></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}} className="mt-7 space-y-4"><label className="block text-sm font-bold">البريد الإلكتروني<input required type="email" data-testid="input-auth-email" className="mt-2 w-full rounded-xl border bg-background px-4 py-3 outline-none focus:ring-2 focus:ring-primary" placeholder="name@example.com"/></label><label className="block text-sm font-bold">كلمة المرور<input required type="password" data-testid="input-auth-password" className="mt-2 w-full rounded-xl border bg-background px-4 py-3 outline-none focus:ring-2 focus:ring-primary" placeholder="••••••••"/></label><button className="w-full rounded-xl bg-primary py-3.5 font-bold text-primary-foreground" data-testid="button-submit-auth">{state.mode==='login'?'دخول إلى حسابي':'إنشاء حسابي'}</button></form>}</motion.div></motion.div>; }

function Assistant({close,openAuth}:{close:()=>void;openAuth:()=>void}){const answers=['منصة «مَتِين» هي أول منصة تعليمية تفاعلية تدمج بين أصالة المتون والمنظومات العلمية وتقنيات الذكاء الاصطناعي الحديثة ومحركات النطق الصوتي؛ لتوفير بيئة متكاملة لطلاب العلم لضبط وتكرار ومراجعة حفظهم للمتون الشرعية بإشراف وتوجيه مشايخ موثوقين.','تستهدف المنصة جميع طلاب وطالبات العلم الشرعي في مختلف المستويات؛ بدءاً من المبتدئين الراغبين في ضبط صغار المتون، وحتى المتقدمين والمستظهرين للمنظومات.','نحرص في «مَتِين» على أعلى معايير الوثوقية والضبط العلمي؛ حيث يُشترط لانضمام المشايخ والمعلمين الحصول على إجازات علمية معتمدة، وتخضع جميع الإجازات لتدقيق صارم.'];const qs=['ما هي منصة مَتِين؟','لمن منصة مَتِين؟','كيف يتم اختيار المشايخ في المنصة؟'];const [answer,setAnswer]=useState('');const [input,setInput]=useState('');return <motion.aside initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} className="fixed inset-y-0 right-0 z-50 flex w-full max-w-md flex-col border-l bg-card p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-primary">المساعد التعريفي</p><h2 className="font-arabic text-3xl font-bold">اسأل مَتِين</h2></div><button onClick={close} aria-label="إغلاق المساعد" data-testid="button-close-assistant"><X/></button></div><div className="mt-8 space-y-2">{qs.map((q,i)=><button key={q} onClick={()=>setAnswer(answers[i])} className="flex w-full items-center justify-between rounded-xl border p-3 text-right text-sm font-bold transition hover:border-primary hover:bg-primary/5" data-testid={`button-assistant-question-${i}`}>{q}<ChevronLeft size={16} className="text-primary"/></button>)}</div><div className="my-6 flex-1 overflow-auto rounded-2xl bg-muted/60 p-5">{answer?<p className="text-sm leading-8">{answer}</p>:<div className="flex h-full flex-col items-center justify-center text-center text-muted-foreground"><Sparkles size={28} className="mb-3 text-accent"/><p className="text-sm">اختر سؤالاً لتتعرف على مَتِين</p></div>}</div><form onSubmit={e=>{e.preventDefault();if(input.trim())setAnswer('للحصول على إجابات مخصصة والاستفادة الكاملة من قدرات المساعد الذكي وتسميع المتون، يرجى تسجيل الدخول إلى حسابك.');setInput('')}} className="relative"><input value={input} onChange={e=>setInput(e.target.value)} className="w-full rounded-xl border bg-background py-3 pl-12 pr-4 text-sm outline-none focus:ring-2 focus:ring-primary" placeholder="اكتب سؤالك..." data-testid="input-assistant"/><button aria-label="إرسال السؤال" className="absolute left-2 top-2 rounded-lg p-1.5 text-primary" data-testid="button-send-assistant"><Send size={18}/></button></form>{answer?.startsWith('للحصول')&&<button onClick={openAuth} className="mt-3 w-full rounded-xl bg-primary py-3 font-bold text-primary-foreground" data-testid="button-assistant-login">تسجيل الدخول</button>}</motion.aside>; }